# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'NewProjectWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_NewProjectWindow(object):
    def setupUi(self, NewProjectWindow):
        NewProjectWindow.setObjectName("NewProjectWindow")
        NewProjectWindow.setWindowModality(QtCore.Qt.WindowModal)
        NewProjectWindow.resize(604, 434)
        self.buttonBox = QtWidgets.QDialogButtonBox(NewProjectWindow)
        self.buttonBox.setGeometry(QtCore.QRect(230, 370, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.label = QtWidgets.QLabel(NewProjectWindow)
        self.label.setGeometry(QtCore.QRect(180, 20, 261, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_4 = QtWidgets.QLabel(NewProjectWindow)
        self.label_4.setGeometry(QtCore.QRect(50, 110, 119, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(NewProjectWindow)
        self.label_5.setGeometry(QtCore.QRect(50, 190, 119, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_3 = QtWidgets.QLabel(NewProjectWindow)
        self.label_3.setGeometry(QtCore.QRect(50, 150, 119, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.commentBox = QtWidgets.QTextEdit(NewProjectWindow)
        self.commentBox.setGeometry(QtCore.QRect(50, 230, 531, 121))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.commentBox.setFont(font)
        self.commentBox.setTabChangesFocus(True)
        self.commentBox.setObjectName("commentBox")
        self.creatorNameBox = QtWidgets.QTextEdit(NewProjectWindow)
        self.creatorNameBox.setGeometry(QtCore.QRect(170, 150, 191, 26))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.creatorNameBox.setFont(font)
        self.creatorNameBox.setTabChangesFocus(True)
        self.creatorNameBox.setObjectName("creatorNameBox")
        self.productNameBox = QtWidgets.QTextEdit(NewProjectWindow)
        self.productNameBox.setGeometry(QtCore.QRect(170, 110, 191, 26))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.productNameBox.setFont(font)
        self.productNameBox.setTabChangesFocus(True)
        self.productNameBox.setObjectName("productNameBox")
        self.label_2 = QtWidgets.QLabel(NewProjectWindow)
        self.label_2.setGeometry(QtCore.QRect(50, 70, 119, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.projectNameBox = QtWidgets.QLineEdit(NewProjectWindow)
        self.projectNameBox.setGeometry(QtCore.QRect(170, 70, 191, 25))
        self.projectNameBox.setObjectName("projectNameBox")

        self.retranslateUi(NewProjectWindow)
        self.buttonBox.accepted.connect(NewProjectWindow.accept)
        self.buttonBox.rejected.connect(NewProjectWindow.reject)
        QtCore.QMetaObject.connectSlotsByName(NewProjectWindow)
        NewProjectWindow.setTabOrder(self.projectNameBox, self.productNameBox)
        NewProjectWindow.setTabOrder(self.productNameBox, self.creatorNameBox)
        NewProjectWindow.setTabOrder(self.creatorNameBox, self.commentBox)

    def retranslateUi(self, NewProjectWindow):
        _translate = QtCore.QCoreApplication.translate
        NewProjectWindow.setWindowTitle(_translate("NewProjectWindow", "New Project"))
        self.label.setText(_translate("NewProjectWindow", "CECS 543 Metrics Suite New Project"))
        self.label_4.setText(_translate("NewProjectWindow", "Product Name:"))
        self.label_5.setText(_translate("NewProjectWindow", "Comments:"))
        self.label_3.setText(_translate("NewProjectWindow", "Creator:"))
        self.label_2.setText(_translate("NewProjectWindow", "Project Name:"))
