# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UCPPaneNameInput.ui'
#
# Created by: PyQt5 UI code generator 5.15.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_UCPPaneNameInput(object):
    def setupUi(self, UCPPaneNameInput):
        UCPPaneNameInput.setObjectName("UCPPaneNameInput")
        UCPPaneNameInput.resize(308, 138)
        self.label = QtWidgets.QLabel(UCPPaneNameInput)
        self.label.setGeometry(QtCore.QRect(70, 20, 161, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.acceptreject = QtWidgets.QDialogButtonBox(UCPPaneNameInput)
        self.acceptreject.setGeometry(QtCore.QRect(-90, 90, 341, 32))
        self.acceptreject.setOrientation(QtCore.Qt.Horizontal)
        self.acceptreject.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.acceptreject.setObjectName("acceptreject")

        self.acceptreject.accepted.connect(UCPPaneNameInput.accept)
        self.acceptreject.rejected.connect(UCPPaneNameInput.reject)

        self.ucpinput = QtWidgets.QLineEdit(UCPPaneNameInput)
        self.ucpinput.setGeometry(QtCore.QRect(60, 60, 201, 20))
        self.ucpinput.setObjectName("ucpinput")

        self.retranslateUi(UCPPaneNameInput)
        QtCore.QMetaObject.connectSlotsByName(UCPPaneNameInput)

    def retranslateUi(self, UCPPaneNameInput):
        _translate = QtCore.QCoreApplication.translate
        UCPPaneNameInput.setWindowTitle(_translate("UCPPaneNameInput", "Dialog"))
        self.label.setText(_translate("UCPPaneNameInput", "UCP Calculation Name"))
